// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkhrqHQaDv3YyeCnn9kMcMUrcc59o98vA',
    appId: '1:782838567187:web:956b60d3617cb0f09a0ae6',
    messagingSenderId: '782838567187',
    projectId: 'safe-space-8b662',
    authDomain: 'safe-space-8b662.firebaseapp.com',
    storageBucket: 'safe-space-8b662.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYyPKRrnEbJ1VNt3UVuGvstZ5UO4cjx4U',
    appId: '1:782838567187:android:ed48bde32f6d96a59a0ae6',
    messagingSenderId: '782838567187',
    projectId: 'safe-space-8b662',
    storageBucket: 'safe-space-8b662.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr0J1LeMKZ5rzbq40YDiNUgRm5SAAaGrA',
    appId: '1:782838567187:ios:f2eabeaa1891ea9f9a0ae6',
    messagingSenderId: '782838567187',
    projectId: 'safe-space-8b662',
    storageBucket: 'safe-space-8b662.firebasestorage.app',
    iosBundleId: 'com.example.safeSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr0J1LeMKZ5rzbq40YDiNUgRm5SAAaGrA',
    appId: '1:782838567187:ios:f2eabeaa1891ea9f9a0ae6',
    messagingSenderId: '782838567187',
    projectId: 'safe-space-8b662',
    storageBucket: 'safe-space-8b662.firebasestorage.app',
    iosBundleId: 'com.example.safeSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkhrqHQaDv3YyeCnn9kMcMUrcc59o98vA',
    appId: '1:782838567187:web:b1ecb94fb7715c059a0ae6',
    messagingSenderId: '782838567187',
    projectId: 'safe-space-8b662',
    authDomain: 'safe-space-8b662.firebaseapp.com',
    storageBucket: 'safe-space-8b662.firebasestorage.app',
  );
}
